#!/bin/sh
set -e

# Exit early if we don't have app credentials defined
if [ -z "$APP_DB_USER" ] || [ -z "$APP_DB_PASSWORD" ]; then
  echo "APP_DB_USER or APP_DB_PASSWORD not set; skipping custom user creation"
  exit 0
fi

# Optional migrator user defaults to app user if not provided
MIGRATOR_USER="${MIGRATOR_DB_USER:-$APP_DB_USER}"
MIGRATOR_PASSWORD="${MIGRATOR_DB_PASSWORD:-$APP_DB_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_DB_USER') THEN
      CREATE ROLE "$APP_DB_USER" WITH LOGIN PASSWORD '$APP_DB_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$MIGRATOR_USER') THEN
      CREATE ROLE "$MIGRATOR_USER" WITH LOGIN PASSWORD '$MIGRATOR_PASSWORD';
    END IF;
  END;
  \$\$;

  ALTER DATABASE "$POSTGRES_DB" OWNER TO "$MIGRATOR_USER";
  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$APP_DB_USER";
EOSQL

# Apply privileges inside the target database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  GRANT USAGE ON SCHEMA public TO "$APP_DB_USER";
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$APP_DB_USER";
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$APP_DB_USER";
  ALTER DEFAULT PRIVILEGES FOR USER "$MIGRATOR_USER" IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$APP_DB_USER";
  ALTER DEFAULT PRIVILEGES FOR USER "$MIGRATOR_USER" IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "$APP_DB_USER";
EOSQL
